### ISSUE TITLE
Engine crashes when using a texture with high resolution

### ISSUE THREAD

**Issue by MaikuDev0** [JanSeliv/CustomShapeButton#12]
So i was using the plugin and i had set all the textures correctly with the correct parameters but the engine kept crashing with this error:
[UnrealEditor CustomShape Button!`SCustomShape Button::UpdateRawColors_Texture'::`2'::<lambda_1>::operator()() [D:\UnrealProjects\CustomShapeButtonSample_UE5-4\Plugins\CustomShapeButton\Source\CustomShapeButton\Private\SCustomShapeButton.cpp:240] UnrealEditor_CustomShapeButton!UE::Core::Private::Function::TFunctionRefCaller<`SCustomShapeButton::UpdateRawColors_Texture'::`2'::<lambda_1>,void __cdecl(FRHICommandL]

After a lot  of testing i have figured out that the problem was that the texture resolution was too high(1080x1080). I have fixed the issue by resizing the texture to 256x256.
I figured i should post this in case someone else had the same issue with this plugin and also because this wasn't mentioned in the documentation.

**Comment by JanSeliv** [comment]
Hello, I cannot reproduce your crash with [this image](https://i.stack.imgur.com/P5Wwo.png) of 4166x4164 size that I randomly found on the web:
![4k-button](https://github.com/JanSeliv/CustomShapeButton/assets/20540872/92c7ed00-5180-485f-92a9-b9e5776d7f8a)

- [Video](https://github.com/JanSeliv/CustomShapeButton/assets/20540872/b8a25ae9-c723-4443-a8c3-ea5beb334c4c) - where set up this 4k image from scratch for the Sample Project from Releases page

You can download this sample from the video with my 4k button and check if it crashes for you. 
- [Unreal Project from the video](https://github.com/JanSeliv/CustomShapeButton/files/15286458/SampleProject_4k-button_UE5-4.zip) - Requires UE5.4. Unzip, then open `CustomShapeSample.uproject`.
- [Cooked Game from the video](https://drive.google.com/file/d/1v88QQBN8nCyge8KnILfMh2LJ-_-62tYB/view?usp=drive_link) - It's a shipped game, does not require Unreal Engine. Unzip, then open `CustomShapeSample.exe`. (_This link will be invalid soon_).

If samples (both CookedGame and Project) don't crash for you, I suspect it might be something with your image setup. Then check next:
1. Make sure the texture has proper settings. Refer to [Step 3A from doc](https://docs.google.com/document/d/1Ws76obIHRMtsdOjB6YP9K7LTjJR-R56h2uv65PKUBL4/edit#heading=h.i8a5fr380fz). A crash might occur if your heavy texture was unloaded by the engine to free up resources, so make sure 'Never Stream' is enabled.
2. It would be worth verifying if the `Image Size` from the `Style` matches the actual texture size. Refer to [Step 4B from doc](https://docs.google.com/document/d/1Ws76obIHRMtsdOjB6YP9K7LTjJR-R56h2uv65PKUBL4/edit#heading=h.jlxkng80vqbe).
3. If your image is corrupted or its size is not divisible by 2, the engine might crash. Try my 4k image from the video: [link](https://i.stack.imgur.com/P5Wwo.png)

**Comment by MaikuDev0** [comment]
Hey, thank you so much for the response, and sorry for taking so long to reply, but I was working on other parts of my project and I forgot about it.

I tried your suggestions and I found that one of my textures had 'Never stream' to false. Also, I didn't match the 'Image size' to my texture's resolution. The crash was pretty uncommon and it hasn't happened since.
