### ISSUE TITLE
Hover and click not working properly

### ISSUE THREAD

**Issue by LordHeImchen** [JanSeliv/CustomShapeButton#14]
Hi all,
first of all, I love this plugin, since it does exactly what I was looking for!

I closely followed the tutorial in this video: [Custom Shaped Button UE5](https://www.youtube.com/watch?v=Db8prQdXWvo)
Unfortunately, my button does not work as expected. When hovering nothing happens (even though the button should turn red) and only when I hold down the left mouse button and hover the actual hovering state is achieved. Consequently, this leads to not being able to trigger something upon a click event... 

My Image has been set to UI, NoMipMaps and VectorDisplacementmap just as shown in the tutorial.

Do you have any idea on how to resolve this issue?

**Comment by JanSeliv** [comment]
Hello, thank you for raising the issue!

In the video, we download the Sample Project first and then extract the plugin itself into our own project. Instead, could you please launch downloaded project first and see if it works well for you?

If it does, please compare the differences in how the buttons are set up.

It is my project I prepared so developers can see how I use it.

**Comment by LordHeImchen** [comment]
Hi,
thanks for your quick response. I had a look at your project already and tried to set my custom shaped button up the same way. Unfortunately it did not work out. Right now, on the first click hovering is activated and the second click will actually click the custom shaped button...

I think it could be related to Game and UI mode, however I am a total newbie to UE5 - so it is more of a wild guess...

**Comment by JanSeliv** [comment]
@LordHeImchen, you are right, your issue definitely sounds as something related to controller modes and widget focusing.

- How Unreal Engine's rectangular buttons work for you, do you experience any issues with them?
- Could you please send my sample project with your changes? So I will take a look at your setup.

**Comment by carlos422** [comment]
This doesnt work for me, it just flash on and off when i mouse hover

**Comment by LordHeImchen** [comment]
@JanSeliv since I couldn't figure out what went wrong I decided to restart from a blanc project. Again, I followed the instructions of the tutorial and everything worked fine. Also, after your question regarding usual buttons, I figured that suddenly these were not behaving correctly as well.

I think this one is on me, not on your plugin :) 
However, many thanks for your quick replies!
