### ISSUE TITLE
Hovered and Unhovered evets fire while the button is hovered

### ISSUE THREAD

**Issue by andyeremin19** [JanSeliv/CustomShapeButton#17]
Hi! I faced a problem recently - I move my cursor on the button but styles change from hovered to unhovered. I'm 100% sure I remain on the button

**Comment by JanSeliv** [comment]
Hi @andyeremin19,

Thanks for bringing this up, it's an interesting case.

I'll try to fix it if I'm able to reproduce the issue. Could you please send me your texture and share some screenshots of how you set it up? That way, I can try to reproduce it on my end. Any video demonstrating the bug would also help me a lot in understanding the issue.

Also, does this happen every time with a 5/5 repro or only under certain conditions?

**Comment by JanSeliv** [comment]
As I haven't received any further response or details, I will be closing this issue for now. Please feel free to create a new one if you have more information or need further assistance.
