### ISSUE TITLE
Crashing in Packaged Build (Development) for Android Quest 2 (UE 5.3.2)

### ISSUE THREAD

**Issue by ketanyeola** [JanSeliv/CustomShapeButton#18]
I imported the widget WBP_Canvas from your Sample Project for UE 5.3. It works fine in PC and PC-VR. But in a packaged build for Android VR, as soon as I spawn that widget, the project crashes. Is it not made for packaged builds or am I missing something? I am using the UE 5.3 version of the plugin.

**Comment by JanSeliv** [comment]
@ketanyeola, thank you for reporting this issue!

The plugin was tested in packaged builds on Windows and macOS with Unreal Engine 5.3, and no crashes occurred, so it might be specific to the Meta Quest 2 build. 

I don't have this device, so I would need your help in attempting to fix this issue. Could you:

1. Share the callstack that appears when the crash happens?
2. Provide the `.log` file from the Saved directory of your build that contains the logs from the crashed session?
3. Test the latest sample project for UE5.4 (not 5.3) by making a package build and running it on your Android device? The newest plugin version for UE5.4 contains some crash fixes that might help.

**Comment by JanSeliv** [comment]
Closed as haven't received any further response or details
