### ISSUE TITLE
Plugin not working at all in UE 5.3.2

### ISSUE THREAD

**Issue by AhmadRock** [JanSeliv/CustomShapeButton#8]
Hi! I watched the tutorial on how to use your plugin and added it to my project but the widget is not working clicking on it does not do anything at all.. tried debugging with print string too still nothing at all...

**Comment by JanSeliv** [comment]
Hello, did you look at Sample Project I attached in Release page? It's UE5.3.2 as well. Download it to see how buttons are setup. Also, please check documentation you can find here as well, it has precise steps of setup. Let me me please know if Project Sample does not work for you

**Comment by AhmadRock** [comment]
Hi! Sorry for the late reply, I have tried it on your sample project and it worked but on my project it didn't work properly. Now I just clicked on it with the mouse cursor and it didn't print anything but while I am clicking on it I pressed Spacebar on keyboard it printed a string, maybe because of my project settings but I don't know what is different... Btw I am creating mobile touch widget

**Comment by JanSeliv** [comment]
It's hard to say what's happening for your project. Try to
- compare every single setting
- recreate button or even project.
- Finally, 'migrate' (or just copy-paste) all my Content from Sample project to your project to check do widgets and textures that I setup by myself from Sample Project work properly in your project. If they stop working, it's definitely something with your project setup or your textures then

**Comment by AhmadRock** [comment]
Hi! I finally figured out why it was not working properly! I needed to add Focus on UI custom function  to work!! thanks for your help!
